### PR TITLE
Implement DOSKEY functionality

### LINKED ISSUE #396: More window controls
Hello, I'd like to suggest some things about the applications window :
- [x] A minimize button (so we don't have every app at the same time on the desktop)
When minimized, the application will still be visible in the taskbar so I also suggest adding
- [x] A taskbar collapse button (for each application that has at least one window open, a collapse button appears on the right of the application's name on the taskbar so it can hide away all of the open windows and not pollute when you have too many of them open at the same time)
- [x] Maybe move the fullscreen button next to the close button (and the new minimize button ?)
- [x] A setting which allows you to choose where you want to place the close/minimize/maximize buttons
- [x] A "smart wrap" option on the windows where instead of wrapping using characters, it wraps using words

That's it for now i guess, tell me what you think !

### LINKED ISSUE #428: doskey is not working
When having a file with doskey macros

_keys.txt_
```
k1=echo hi
k2=echo hi2
```

`doskey /macrofile=keys.txt`
and then list the defined ones the list comes back empty when running vtm inside Windows Terminal:

With vtm
image

when doing this in a Windows Terminal cmd prompt then it works

With cmd.exe
image

No errors. That is really strange.

### LINKED ISSUE #438: Disable double click toggling window maximization for tui apps with mouse support
Newer versions of `vtm` always toggle window maximization on double click, so I can't use double click normally in some tui applications (such as `vim` with mouse support, or `nnn`)
Older versions (at least in `v0.9.9h`) do not show this behavior

### PR DESCRIPTION
**Pull request by o-sdn-o**
Changes:
- Implemented the following APIs ([DOSKEY.EXE](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/doskey)) support:
  - `AddConsoleAlias`
  - `GetConsoleAlias`
  - `GetConsoleAliasExesLength`
  - `GetConsoleAliasExes`
  - `GetConsoleAliasesLength`
  - `GetConsoleAliases`
  - `ExpungeConsoleCommandHistory`
  - `SetConsoleNumberOfCommands` - not used
  - `GetConsoleCommandHistoryLength`
  - `GetConsoleCommandHistory`
  - `GetConsoleHistoryInfo` - not used
  - `SetConsoleHistoryInfo` - not used
- Alt+F10 to wipe DOSKEY aliases for current process (by process module name).
- Alt+F7 to clear command history (by process module name).
- Processes with the same module name share a common command history.
- Force 16-color mode on MS Windows prior Windows 10.
- Implement word-based text wrapping. #396
- Add GitHub Action workflow to generate binaries for the big three OS platforms.
- Disable mouse event processing when any reporting mode enabled. #438
- Add the ability to change default menu item settings. #439

Closes #396
Closes #428
Closes #438

### CODE REVIEW

**Comment by AloisKraus** [comment]
When I try this PR i get compilation errors. Is this a problem with my setup? 

```
C:\source\vtm>cmake --build bin --config Release
MSBuild version 17.6.3+07e294721 for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/source/vtm/CMakeLists.txt
  vtm.cpp
C:\source\vtm\src\netxs\desktopio\canvas.hpp(1579,80): error C2131: expression did not evaluate to a constant [C:\source\vtm\bin\vtm.vcxproj]
C:\source\vtm\src\netxs\desktopio\canvas.hpp(168,49): message : a non-constant (sub-)expression was encountered [C:\source\vtm\bin\vtm.vcxproj]
C:\source\vtm\src\netxs\desktopio\logger.hpp(99,1): error C3313: 'state': variable cannot have the type 'void' [C:\source\vtm\bin\vtm.vcxproj]
C:\source\vtm\src\netxs\desktopio\logger.hpp(100,1): error C3536: 'state': cannot be used before it is initialized [C:\source\vtm\bin\vtm.vcxproj]
C:\source\vtm\src\netxs\desktopio\logger.hpp(110,1): error C3313: 'state': variable cannot have the type 'void' [C:\source\vtm\bin\vtm.vcxproj]
C:\source\vtm\src\netxs\desktopio\logger.hpp(111,1): error C3536: 'state': cannot be used before it is initialized [C:\source\vtm\bin\vtm.vcxproj]
C:\source\vtm\src\netxs\desktopio\logger.hpp(115,1): error C3313: 'state': variable cannot have the type 'void' [C:\source\vtm\bin\vtm.vcxproj]
C:\source\vtm\src\netxs\desktopio\logger.hpp(116,1): error C3536: 'state': cannot be used before it is initialized [C:\source\vtm\bin\vtm.vcxproj]

```

**Comment by o-sdn-o** [comment]
You may need to update Visual Studio.

My setup (MSBuild version 17.7.2):
```
D:\sources\test\vstest>cmake --build bin --config Release
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  Checking Build System
  Building Custom Rule D:/sources/test/vstest/CMakeLists.txt
  vtm.cpp
  vtm.vcxproj -> D:\sources\test\vstest\bin\Release\vtm.exe
  Building Custom Rule D:/sources/test/vstest/CMakeLists.txt

D:\sources\test\vstest>
```

**Comment by o-sdn-o** [comment]
Make sure checkout branch `o-sdn-o:vt-input-mode`:

```
D:\sources\test\vstest>git rev-parse --abbrev-ref HEAD
vt-input-mode

D:\sources\test\vstest>
```

**Comment by o-sdn-o** [comment]
I'll configure github actions for automatic building and it will be easier to test.

**Comment by o-sdn-o** [comment]
Now you can just download the binary fron 'All checks have passed -> Details -> Summary -> Artifacts'

image

**Comment by AloisKraus** [comment]
looks good now. No errors are showing up anymore. 
That is great work. Thanks!

**Pull request merged**
